add rs code validation to git hooks and GH workflow

diff --git a/.husky/configs/helpers b/.husky/configs/helpers
--- a/.husky/configs/helpers
+++ b/.husky/configs/helpers
@@ -5,11 +5,11 @@
 validate () {
   for COMMAND in "$@"; do
    printf "🤞 Running: $COMMAND \n"
-   if ! yarn $COMMAND
+   if ! $COMMAND
    then
-       printf "👎 ${RED} Failed: $COMMAND \n${NC}"
+       printf "⛔ ${RED} Failed to check: $COMMAND \n${NC}"
        exit 1
    fi
-   printf "👏 ${GREEN} Success: $COMMAND \n\n${NC}"
+   printf "✅ ${GREEN} Success: $COMMAND \n\n${NC}"
   done
 }
